### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by unhuman** [mbland/custom-links#161]
It'd be great if we could search.

**Comment by mbland** [comment]
There's two types of search we need:

* A search on target/destination links per #165.
* A search on short links, to enable features like #160.

Also, introducing tags per #162 may introduce a third search, but that's lower priority.

Focusing on the search on short links, the `RedisClient.getLinks()` method added in #163 does most of the backend heavy lifting already. We can expand upon that method to take a regex as a parameter to replace the hardcoded `/*` string. Then we need to figure out how to expose an API endpoint and a UI element.

I hope to make progress on #167 in the near future to make working with this code easier.

cc: @akashvbabu @mpdatx

**Comment by mbland** [comment]
Chatted with @akashvbabu, here's our current plan:

- [ ] Add a `/api/search` backend method. An option will select between custom link and target URL search.
- [ ] Add a `#search` view for the `/api/search` method. Include a client-side control to search short links or target links.

We'll decide later whether we need any autocomplete capabilities.
